### PR TITLE
Replace emdash with hyphen

### PR DESCRIPTION
**Pull request by paulgear**
*Issue #, if available:*

*Description of changes:*

Make the wget command cut & paste friendly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alcousins** [comment]
Thanks for this! taking a look and i'll merge shortly

**Comment by paulgear** [comment]
Thanks Alastair.  I have some more suggestions in the pipeline, which I've made while preparing to re-present your content to my workmates.  I'll get a PR up in the next few days, but in the meantime you can see what I've been doing here: https://github.com/aws-samples/linux-container-primitives-presentation-notebooks/compare/master...paulgear:master

**Comment by alcousins** [comment]
Awesome, that sounds interesting!

Just looking at this patch, i suspect this is me/my browser/environment, but in the diff i see the '-' character as a hyphen in both the remove and add lines.. just wanted to validate, what environment are you seeing the original as an emdash in, or how are you copy/pasting to get that scenario? I'd like to repro it also just so i can work backwards to how it got like this! (for reference, i've written all this on a mac in vscode).

**Comment by paulgear** [comment]
Here's a hexdump of what I see - note the `e2 80 93 6e` in your commit vs. the `2d 6e` in mine.
```
$ git diff 061e7554b34884257a5b80b0533a72cf96423d4c 102ce4c9376d60583026f70d78645d93d9c5fb81 | hexdump -C
00000000  64 69 66 66 20 2d 2d 67  69 74 20 61 2f 52 45 41  |diff --git a/REA|
00000010  44 4d 45 2e 6d 64 20 62  2f 52 45 41 44 4d 45 2e  |DME.md b/README.|
00000020  6d 64 0a 69 6e 64 65 78  20 36 66 33 62 34 33 30  |md.index 6f3b430|
00000030  2e 2e 64 32 31 63 65 31  31 20 31 30 30 36 34 34  |..d21ce11 100644|
00000040  0a 2d 2d 2d 20 61 2f 52  45 41 44 4d 45 2e 6d 64  |.--- a/README.md|
00000050  0a 2b 2b 2b 20 62 2f 52  45 41 44 4d 45 2e 6d 64  |.+++ b/README.md|
00000060  0a 40 40 20 2d 32 38 2c  37 20 2b 32 38 2c 37 20  |.@@ -28,7 +28,7 |
00000070  40 40 20 54 68 65 20 66  6f 6c 6c 6f 77 69 6e 67  |@@ The following|
00000080  20 63 6f 6d 6d 61 6e 64  73 20 68 61 76 65 20 62  | commands have b|
00000090  65 65 6e 20 74 65 73 74  65 64 20 73 75 63 63 65  |een tested succe|
000000a0  73 73 66 75 6c 6c 79 20  74 6f 20 63 6f 6e 66 69  |ssfully to confi|
000000b0  67 75 72 65 20 74 68 65  20 68 6f 73 74 20 4f 53  |gure the host OS|
000000c0  20 74 6f 0a 20 45 6e 61  62 6c 65 20 45 50 45 4c  | to. Enable EPEL|
000000d0  20 72 65 70 6f 73 69 74  6f 72 79 3a 0a 20 7e 7e  | repository:. ~~|
000000e0  7e 7e 0a 20 63 64 20 2f  74 6d 70 0a 2d 77 67 65  |~~. cd /tmp.-wge|
000000f0  74 20 2d 4f 20 65 70 65  6c 2e 72 70 6d 20 e2 80  |t -O epel.rpm ..|
00000100  93 6e 76 20 5c 0a 2b 77  67 65 74 20 2d 4f 20 65  |.nv \.+wget -O e|
00000110  70 65 6c 2e 72 70 6d 20  2d 6e 76 20 5c 0a 20 68  |pel.rpm -nv \. h|
00000120  74 74 70 73 3a 2f 2f 64  6c 2e 66 65 64 6f 72 61  |ttps://dl.fedora|
00000130  70 72 6f 6a 65 63 74 2e  6f 72 67 2f 70 75 62 2f  |project.org/pub/|
00000140  65 70 65 6c 2f 65 70 65  6c 2d 72 65 6c 65 61 73  |epel/epel-releas|
00000150  65 2d 6c 61 74 65 73 74  2d 37 2e 6e 6f 61 72 63  |e-latest-7.noarc|
00000160  68 2e 72 70 6d 0a 20 73  75 64 6f 20 79 75 6d 20  |h.rpm. sudo yum |
00000170  69 6e 73 74 61 6c 6c 20  2d 79 20 2e 2f 65 70 65  |install -y ./epe|
00000180  6c 2e 72 70 6d 0a 20 7e  7e 7e 7e 0a              |l.rpm. ~~~~.|
0000018c
```

**Pull request closed without merging**
